language: java
sudo: required
jdk:
 - oraclejdk8
before_install: sudo apt-get update; mysql -e "create database IF NOT EXISTS unqdb;" -uroot
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
  - "mysql -uroot -e \"DELETE FROM mysql.db WHERE Db = 'unqdb\\_%';\""
  - "mysql -uroot -e \"DELETE FROM mysql.user WHERE Host = 'localhost' AND User = '';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS unqdb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"GRANT ALL PRIVILEGES ON unqdb.* TO 'admin'@'localhost' IDENTIFIED BY 'admin';\""
  - "mysql -uroot -e \"CREATE DATABASE IF NOT EXISTS unqdb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;\""
  - "mysql -uroot -e \"DELETE FROM mysql.user WHERE User = 'travis';\""
  - "mysql -uroot -e \"FLUSH PRIVILEGES;\""
script:
  - mvn test -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
install: mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
after_script:
  - cp target/site/jacoco/jacoco.xml .
  - git clone https://github.com/codacy/codacy-coverage-reporter.git
  - cd codacy-coverage-reporter/
  - sbt assembly
  - cd ..
  - java -cp codacy-coverage-reporter/target/codacy-coverage-reporter-assembly-1.0.5.jar com.codacy.CodacyCoverageReporter -l Java -r jacoco.xml
