language: java
sudo: required
dist: trusty
jdk:
 - oraclejdk8
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
services:
  - mysql
before_install:
  - sudo apt-get update;
  - mysql -u root -e "create database unqdb;"
  - mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -u root -e "grant all on unqdb.* to admin@localhost identified by 'admin';"
script:
  - mvn clean install compile test -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
