language: java
sudo: required
jdk:
 - oraclejdk8
before_install:
  -sudo apt-get update
  - mysql -u root -e "create database IF NOT EXISTS unqdb;"
dist: trusty
services:
  - mysql
install: mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
before_script:
  - mysql -u root -e 'CREATE DATABASE unqdb;'
  - mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON unqdb.* TO 'admin'@'localhost' IDENTIFIED BY 'admin' WITH GRANT OPTION;"
  - mysql -u root -e "FLUSH PRIVILEGES";
script: mvn test -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
after_script:
  - cp target/site/jacoco/jacoco.xml .
  - git clone https://github.com/codacy/codacy-coverage-reporter.git
  - cd codacy-coverage-reporter/
  - sbt assembly
  - cd ..
  - java -cp codacy-coverage-reporter/target/codacy-coverage-reporter-assembly-1.0.5.jar com.codacy.CodacyCoverageReporter -l Java -r jacoco.xml