language: java
sudo: required
jdk:
 - oraclejdk8
before_install: sudo apt-get update;
dist: trusty
services:
  - mysql
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
  - mysql -e 'create database unqdb;'
  - mysql -u travis -e "create database unqdb;"
  - mysql -u travis -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin';"
  - mysql -u travis -e "grant all on unqdb.* to admin@localhost identified by 'admin';"
script:
  - mvn test -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
install: mvn install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
after_script:
  - cp target/site/jacoco/jacoco.xml .
  - git clone https://github.com/codacy/codacy-coverage-reporter.git
  - cd codacy-coverage-reporter/
  - sbt assembly
  - cd ..
  - java -cp codacy-coverage-reporter/target/codacy-coverage-reporter-assembly-1.0.5.jar com.codacy.CodacyCoverageReporter -l Java -r jacoco.xml
